version: "3"
services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.port=8000"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=iot
  app:
      build: .
      command: bash -c 'uvicorn src.main:app --host 0.0.0.0'
      volumes:
        - .:/code
      expose:
        - 8000
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.fastapi.rule=Host(`${WHOAMI_IP}`)"
          - "traefik.port=8080"
      depends_on:
        - postgres
      restart: on-failure
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "5050:5050"
      depends_on:
        - postgres