### 
GET {{host}}{{port}}
Accept: application/json

### 
POST {{host}}{{port}}/sensor/
Accept: application/json

{
    "sensor_name": "Válvula solenoide",
    "tag": "SVC506",
    "value": 1.90,
    "unit": "1m2"
}

###
PUT {{host}}{{port}}/sensor/?sensorId=100
Accept: application/json

{
    "sensor_name": "Válvula solenoide",
    "tag": "SVC50015",
    "value": 1.90,
    "unit": "1m2"
}


###
POST {{host}}{{port}}/operation/sensor/analogic
Accept: application/json

{
    "sensor_name": "Válvula solenoide",
    "tag": "SVC507",
    "value": 1.80,
    "unit": "1m2"
}